FROM rockylinux:9
#FROM almalinux:9

# set yes or no
ENV WITH_DESKTOP=yes

# set Gnome, KDE or Xfce
ENV DESKTOP_FlAVOUR=Gnome

###################################

RUN dnf update -y
RUN dnf install epel-release -y
RUN crb enable
RUN dnf install systemd htop -y


COPY inst-Desktop.brc /
RUN source /inst-Desktop.brc && installDesktop $WITH_DESKTOP $DESKTOP_FlAVOUR

CMD ["/usr/lib/systemd/systemd"]

