FROM rockylinux:9
#FROM almalinux:9

# set yes or no
ENV WITH_DESKTOP=yes

# set Gnome, KDE or Xfce
ENV DESKTOP_FlAVOUR=Gnome

RUN dnf update -y
RUN dnf install epel-release -y
RUN crb enable
RUN dnf install systemd htop -y


RUN if [ "$WITH_DESKTOP" = "yes" ]; then \




CMD ["/usr/lib/systemd/systemd"]

